// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasePage: typeof import('./src/components/personPage/basePage.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElM: typeof import('element-plus/es')['ElM']
    ElMe: typeof import('element-plus/es')['ElMe']
    ElMen: typeof import('element-plus/es')['ElMen']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    'ElMenu-': typeof import('element-plus/es')['ElMenu-']
    ElMenuI: typeof import('element-plus/es')['ElMenuI']
    ElMenuIt: typeof import('element-plus/es')['ElMenuIt']
    ElMenuIte: typeof import('element-plus/es')['ElMenuIte']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    Header: typeof import('./src/components/personPage/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/personPage/Home.vue')['default']
    LeftSidebar: typeof import('./src/components/personPage/leftSidebar.vue')['default']
    Main: typeof import('./src/components/main.vue')['default']
    RightSidebar: typeof import('./src/components/personPage/rightSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar.vue')['default']
  }
}
